print(" Twinkle,twinklle,little star,")
print("    How I wonder what you")
print(" are!")
print("    Up above the world so ")
print(" high,")
print("    Like a dimond in the")
print(" sky.")
print(" Twinkle,twinklle,little star,")
print("   How I wonder what you")
print(" are")
